exclude: |
  (?x)(
    .*/migrations
  )

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ['--maxkb=2000']
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
        exclude: .*/templates
      - id: debug-statements
      - id: end-of-file-fixer
      #  - id: requirements-txt-fixer
      - id: flake8
        args: ['--max-line-length=140']  # default of Black
      - id: mixed-line-ending
      - id: pretty-format-json
        args: ['--autofix', '--no-sort-keys', '--no-ensure-ascii']
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: [-m=VERTICAL_HANGING_INDENT, --skip=seed/models/__init__.py, --filter-files]
