repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=2000"]
      - id: check-ast
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
        exclude: .*/templates
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: seed/static/seed/locales/
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        exclude: seed/static/seed/locales/
      - id: pretty-format-json
        args: ["--autofix", "--no-sort-keys", "--no-ensure-ascii"]
        exclude: seed/static/seed/locales/
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        # for now ignoring html, javascript
        types_or: [yaml, markdown, css, scss]
  # https://docs.astral.sh/ruff/integrations/#pre-commit
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.1
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --output-format=full]
      # Run the formatter
      - id: ruff-format
