apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: db-postgres
  name: db-postgres
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      io.kompose.service: db-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: db-postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: seed
            - name: POSTGRES_PASSWORD
              value: super-secret-password
            - name: POSTGRES_USER
              value: seeduser
          image: timescale/timescaledb-postgis:latest-pg12
          imagePullPolicy: Always
          name: db-postrgres
          #        command: ["tail"]
          #        args: ['-f', '/dev/null']
          ports:
            - containerPort: 5432
              protocol: TCP
          resources:
            limits:
              cpu: 300m
            requests:
              cpu: 300m
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: seed-pgdata
            - mountPath: /seed-backups/backups
              name: seed-backups
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: seed-pgdata
          persistentVolumeClaim:
            claimName: seed-pgdata
        - name: seed-backups
          hostPath:
            path: /etc/seedbackups
status: {}
