apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: db-postgres
  name: db-postgres
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: db-postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: seed
        - name: POSTGRES_PASSWORD
          value: super-secret-password
        - name: POSTGRES_USER
          value: seed
        image: timescale/timescaledb-postgis:latest-pg12
        imagePullPolicy: Always
        name: db-postrgres
#        command: ["tail"]
#        args: ['-f', '/dev/null']
        ports:
        - containerPort: 5432
        resources:
          limits:
            cpu: "300m"
          requests:
            cpu: "300m"
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: seed-pgdata
      restartPolicy: Always
      volumes:
      - name: seed-pgdata
        persistentVolumeClaim:
          claimName: seed-pgdata
status: {}
